import streamlit as st
st.title(':rainbow[V]ijaya :rainbow[S]ri :rainbow[M]anda')
st.write("Email: [vijayasrimanda025@gmail.com](vijayasrimanda025@gmail.com)")
st.write("LinkedIn: [www.linkedin.com](https://www.linkedin.com/in/vijaya-sri-manda-399a56343/)")
st.write("GitHub: [https://github.com/vijayasri-manda](https://github.com/vijayasri-manda)")
st.markdown("<hr>",unsafe_allow_html=True)
st.markdown("### Objective:")
st.write("Aspiring AI & Full Stack developer seeking a challenge role to leverage my skills in machine learning,web development,and software engineering.Eager to contribute to innovative projects,grow professionally,and apply academic knowledge in real-world applications.")

st.markdown("<hr>",unsafe_allow_html=True)
st.markdown("### Education")
st.markdown("<ul><li><dl><dt>Seshadri Rao Gudlavalleru Engineering College</dt><dd>- Btech In Artificial Intelligence and Data Science - 87.9</dd></dl></li></ul>",unsafe_allow_html=True)
st.markdown("<ul><li><dl><dt>VKR,VNB & AGK College Of Engineering</dt><dd>- Diploma in Computer Engineering - 91.3</dd></dl></li></ul>",unsafe_allow_html=True)
st.markdown("<ul><li><dl><dt>Dr.K.K.R 's Gowtham Concept School</dt><dd>Secondary School Of Education - 10</dd></dl></li></ul>",unsafe_allow_html=True)
st.markdown("<hr>",unsafe_allow_html=True)
st.markdown("### Technical Skills")
st.markdown("<ul><li>Python</li><li>Java</li><li>C++</li><li>C</li></ul>",unsafe_allow_html=True)
st.markdown("<hr>",unsafe_allow_html=True)
st.markdown("<h3>Experience:</h3><p> - Intern at AIMER Society</p>",unsafe_allow_html=True)
st.markdown("<hr>",unsafe_allow_html=True)
st.markdown("### 📜Certifications:")
st.markdown("<ul><li>HTML,CSS,JavaScript and SQL from Moral Institute of technology recognised by Andhra Pradesh Government.</li><li>Python Certificate from Hacker rank</li></ul>",unsafe_allow_html=True)
if st.button("Send balloons!"):
    st.balloons()
